apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap  # Correct mode for using an Access Point
  fileSystemId: "fs-079d266bde1dd0e12"  # Separate parameter for the FileSystem ID
  accessPointId: "fsap-0cf97273243628ba8"  # Separate parameter for the Access Point ID
  directoryPerms: "777"  # Permissions for the directory
