# Secrets for Postgres
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
type: Opaque # This is the most common type of secret TODO: Research other types
data:
  username: cG9zdGdyZXM=
  password: YWRtaW4xMjM0
