# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the Docker image
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY /job_monitoring_app/frontend/package*.json ./
COPY /job_monitoring_app/frontend/public ./public
COPY /job_monitoring_app/frontend/src ./src
COPY /job_monitoring_app/frontend/fixtures ./fixtures
COPY /job_monitoring_app/frontend/next.config.js ./
COPY /job_monitoring_app/frontend/tsconfig.json ./


# Install the application dependencies
RUN npm install


# Expose port 3000 for the application
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]
