# Use a Python 3.10 image based on Debian slim as the base
FROM python:3.10-slim
LABEL authors="iejohnson"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-dev \
    inetutils-ping \
    curl \
    net-tools\
    dnsutils\
    # Clean up the apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# TODO: Seperate requirements for OrthancReciever and TrackerAPI from the generic backend requirements file
# Copy the Python requirements file into the container
COPY job_monitoring_app/trackerapi/requirements.txt requirements_tracker.txt
COPY internal_servers/requirements.txt requirements_receiver.txt

# Install the Python dependencies
RUN pip3 install --no-cache-dir -r requirements_tracker.txt -r requirements_receiver.txt

# Copy the trackerapi code into the container
COPY job_monitoring_app/trackerapi /app/internal_servers/job_monitoring_app/trackerapi

# Copy the receiver code into the container

# Copy the executable script into the container
COPY example_run_brain_mask_tool_light_docker.sh runner.sh
RUN chmod +x runner.sh

COPY internal_servers/hospital_job_configuration.json ./internal_servers/hospital_job_configuration.json
COPY internal_servers/job-configurations-schema.generated.json ./internal_servers/job-configurations-schema.generated.json
COPY internal_servers/study.py /app/internal_servers/study.py
COPY internal_servers/util_functions.py /app/internal_servers/util_functions.py
COPY internal_servers/receiver_loop.py /app/internal_servers/receiver_loop.py
COPY internal_servers/__init__.py  /app/internal_servers/__init__.py

# Set the PYTHON_PATH environment variable
ENV PYTHONPATH=/app/internal_servers

ARG DEBIAN_FRONTEND=noninteractive
ARG API_KEY
ARG BACKEND_URL
ARG ORTHANC_URL
ARG hospital_mapping_file
ARG study_config_file



CMD ["python3", "internal_servers/receiver_loop.py", "--api_key", "${API_KEY}", "--backend_url", "${BACKEND_URL}", "--orthanc_url", "${ORTHANC_URL}", "--hospital_mapping_file", "${hospital_mapping_file}", "--study_config_file", "${study_config_file}"]
