# Volume Definition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/imagepro/postgres"
  storageClassName: aws-efs # this is the default storage class
