# StatefulSet Definition
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: pg_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: pg_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata  # Set PGDATA to match your volume mount path
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data  # Mount the PVC to the directory where PostgreSQL stores its data
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: postgres-pvc
