"""Create Studies, drop Jobs, modify event and job_configuration

Revision ID: 0dc878d76b15
Revises: f5e0f22bbaea
Create Date: 2024-02-29 12:45:34.366367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0dc878d76b15"
down_revision = "f5e0f22bbaea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the studies table
    op.create_table(
        "studies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_study_id", sa.String(), nullable=False),
        sa.Column("provider_study_name", sa.String(), nullable=True),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column("job_configuration_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_configuration_id"], ["job_configurations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "provider_study_id"),
    )
    op.create_index(
        op.f("ix_studies_hospital_id"), "studies", ["hospital_id"], unique=False
    )
    op.create_index(op.f("ix_studies_id"), "studies", ["id"], unique=False)
    op.create_index(
        op.f("ix_studies_job_configuration_id"),
        "studies",
        ["job_configuration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_studies_provider_id"), "studies", ["provider_id"], unique=False
    )
    op.create_index(
        op.f("ix_studies_provider_study_id"),
        "studies",
        ["provider_study_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_studies_provider_study_name"),
        "studies",
        ["provider_study_name"],
        unique=False,
    )
    # Drop the jobs table

    op.drop_index("ix_jobs_customer_id", table_name="jobs")
    op.drop_index("ix_jobs_id", table_name="jobs")
    op.drop_index("ix_jobs_job_configuration_id", table_name="jobs")
    op.drop_index("ix_jobs_provider_id", table_name="jobs")
    op.drop_index("ix_jobs_provider_job_id", table_name="jobs")
    op.drop_index("ix_jobs_provider_job_name", table_name="jobs")
    op.drop_table("jobs")

    # Modify the event table
    op.add_column("events", sa.Column("study_id", sa.Integer(), nullable=False))
    op.drop_index("ix_events_job_id", table_name="events")
    op.create_index(op.f("ix_events_study_id"), "events", ["study_id"], unique=False)
    op.drop_constraint("events_job_id_fkey", "events", type_="foreignkey")
    op.create_foreign_key(None, "events", "studies", ["study_id"], ["id"])
    op.drop_column("events", "job_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the jobs table
    op.add_column(
        "events", sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "events", type_="foreignkey")
    op.create_foreign_key("events_job_id_fkey", "events", "jobs", ["job_id"], ["id"])
    op.drop_index(op.f("ix_events_study_id"), table_name="events")
    op.create_index("ix_events_job_id", "events", ["job_id"], unique=False)
    op.drop_column("events", "study_id")
    op.create_table(
        "jobs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("provider_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("provider_job_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "provider_job_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "job_configuration_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["users.id"], name="jobs_customer_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["job_configuration_id"],
            ["job_configurations.id"],
            name="fk_jobs_job_configuration_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["users.id"], name="jobs_provider_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="jobs_pkey"),
        sa.UniqueConstraint(
            "provider_id",
            "provider_job_id",
            name="jobs_provider_id_provider_job_id_key",
        ),
    )
    op.create_index(
        "ix_jobs_provider_job_name", "jobs", ["provider_job_name"], unique=False
    )
    op.create_index(
        "ix_jobs_provider_job_id", "jobs", ["provider_job_id"], unique=False
    )
    op.create_index("ix_jobs_provider_id", "jobs", ["provider_id"], unique=False)
    op.create_index(
        "ix_jobs_job_configuration_id", "jobs", ["job_configuration_id"], unique=False
    )
    op.create_index("ix_jobs_id", "jobs", ["id"], unique=False)
    op.create_index("ix_jobs_customer_id", "jobs", ["customer_id"], unique=False)
    # Drop the studies table
    op.drop_index(op.f("ix_studies_provider_study_name"), table_name="studies")
    op.drop_index(op.f("ix_studies_provider_study_id"), table_name="studies")
    op.drop_index(op.f("ix_studies_provider_id"), table_name="studies")
    op.drop_index(op.f("ix_studies_job_configuration_id"), table_name="studies")
    op.drop_index(op.f("ix_studies_id"), table_name="studies")
    op.drop_index(op.f("ix_studies_hospital_id"), table_name="studies")
    op.drop_table("studies")
    # ### end Alembic commands ###
