"""add study configuration id to study table

Revision ID: 23375153341b
Revises: 8199c3285ce8
Create Date: 2024-03-05 12:05:45.597345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23375153341b"
down_revision = "8199c3285ce8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "studies",
        sa.Column("study_configuration_id", sa.Integer(), nullable=True),
    )

    # Retrieve the studies table
    studies_table = sa.Table("studies", sa.MetaData(), autoload_with=op.get_bind())

    # Update the study_configuration_id column with the value from job_configuration_id
    update_stmt = studies_table.update().values(
        study_configuration_id=studies_table.c.job_configuration_id
    )
    op.execute(update_stmt)

    op.create_index(
        op.f("ix_studies_study_configuration_id"),
        "studies",
        ["study_configuration_id"],
        unique=False,
    )
    sa.ForeignKeyConstraint(
        ["study_configuration_id"],
        ["study_configurations.id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # drop study configuration id from studies
    op.drop_index(
        op.f("ix_studies_study_configuration_id"),
        table_name="studies",
    )
    op.drop_column("studies", "study_configuration_id")
    # ### end Alembic commands ###
