"""add pacs, connect to hospital"


Revision ID: 39be54721c3e
Revises: f3e2baca00c3
Create Date: 2024-03-07 11:57:14.881597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "39be54721c3e"
down_revision = "f3e2baca00c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create the pacs table
    op.create_table(
        "pacs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pacs_name", sa.String(), nullable=False),
        sa.Column("hospital_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["hospital_id"],
            ["hospitals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pacs_hospital_id"), "pacs", ["hospital_id"], unique=False)
    op.create_index(op.f("ix_pacs_id"), "pacs", ["id"], unique=False)
    op.create_index(op.f("ix_pacs_pacs_name"), "pacs", ["pacs_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # drop the pacs table
    op.drop_index(op.f("ix_pacs_pacs_name"), table_name="pacs")
    op.drop_index(op.f("ix_pacs_id"), table_name="pacs")
    op.drop_index(op.f("ix_pacs_hospital_id"), table_name="pacs")
    op.drop_table("pacs")
    # ### end Alembic commands ###
