"""remove job_id from events

Revision ID: 85c67626ddb1
Revises: 12b9270616c1
Create Date: 2024-03-01 17:49:58.398920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85c67626ddb1"
down_revision = "12b9270616c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the job_id column from the events table
    op.drop_index("ix_events_job_id", table_name="events")
    op.drop_constraint("events_job_id_fkey", "events", type_="foreignkey")
    op.drop_column("events", "job_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "job_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            server_default="0",
        ),
    )

    # Retrieve the events table
    events_table = sa.Table("events", sa.MetaData(), autoload_with=op.get_bind())

    # Update the study_id column with the value from job_id
    update_stmt = events_table.update().values(job_id=events_table.c.study_id)
    op.execute(update_stmt)

    op.create_foreign_key("events_job_id_fkey", "events", "jobs", ["job_id"], ["id"])
    op.create_index("ix_events_job_id", "events", ["job_id"], unique=False)

    # ### end Alembic commands ###
