"""Create hospitals table

Revision ID: ba0e58261155
Revises: 593cd73ffb81
Create Date: 2024-03-05 16:37:25.989828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba0e58261155"
down_revision = "593cd73ffb81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create hospitals table
    op.create_table(
        "hospitals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hospital_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hospitals_hospital_name"), "hospitals", ["hospital_name"], unique=False
    )
    op.create_index(op.f("ix_hospitals_id"), "hospitals", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # drop hospitals table
    op.drop_index(op.f("ix_hospitals_id"), table_name="hospitals")
    op.drop_index(op.f("ix_hospitals_hospital_name"), table_name="hospitals")
    op.drop_table("hospitals")
    # ### end Alembic commands ###
