"""move data from job config to study config

Revision ID: f6e8ae66a187
Revises: 23375153341b
Create Date: 2024-03-05 13:10:03.536281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6e8ae66a187"
down_revision = "23375153341b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Assuming 'job_configurations' and 'study_configurations' tables have compatible schemas.
    # Adjust the column names in the select statement if necessary to match the target table's schema.
    # insert data from job_configurations to study_configurations
    insert_stmt = sa.sql.text(
        """
            INSERT INTO study_configurations (id, tag, name, provider_id, version)
            SELECT id, tag, name, provider_id, version FROM job_configurations
        """
    )
    op.execute(insert_stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
