"""move data from jobs to studies

Revision ID: f835537a4c9a
Revises: 85c67626ddb1
Create Date: 2024-03-04 12:05:10.061300

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f835537a4c9a"
down_revision = "85c67626ddb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Assuming 'jobs' and 'studies' tables have compatible schemas.
    # Adjust the column names in the select statement if necessary to match the target table's schema.
    # insert data from jobs to studies
    insert_stmt = sa.sql.text(
        """
            INSERT INTO studies (id, provider_id, provider_study_id, provider_study_name, hospital_id, job_configuration_id)
            SELECT id, provider_id, provider_job_id, provider_job_name, customer_id, job_configuration_id FROM jobs
        """
    )
    op.execute(insert_stmt)
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    pass
