# Use a Python 3.10 image based on Debian slim as the base
FROM python:3.10-slim
LABEL authors="mbrzus and iejohnson"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-dev \
    inetutils-ping \
    curl \
    net-tools\
    dnsutils\
    # Clean up the apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install the Python dependencies
RUN pip3 install --no-cache-dir pyorthanc typing_extensions requests

# Copy the executable script into the container
COPY hospital_job_configuration.json ./small_k8s_system/hospital_job_configuration.json
COPY job-configurations-schema.generated.json ./small_k8s_system/job-configurations-schema.generated.json
COPY receiver_loop.py ./small_k8s_system/receiver_loop.py
COPY util_functions.py ./small_k8s_system/util_functions.py

# Set the PYTHON_PATH environment variable
ENV PYTHONPATH=/app/small_k8s_system
#ENV DOCKER_ENV=1
#ARG DEBIAN_FRONTEND=noninteractive
#ARG API_KEY
#ARG BACKEND_URL
#ARG ORTHANC_URL

# Set default parameters that can be overridden
ENTRYPOINT ["python", "/app/small_k8s_system/receiver_loop.py"]
