# Use a Python 3.10 image based on Debian slim as the base
FROM python:3.10-slim
LABEL authors="mbrzus and iejohnson"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-dev \
    inetutils-ping \
    curl \
    net-tools\
    dnsutils\
    # Clean up the apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install the Python dependencies
RUN pip3 install --no-cache-dir pyorthanc typing_extensions

# Copy the receiver code into the container

# Copy the executable script into the container
COPY ../internal_servers/hospital_job_configuration.json ./internal_servers/hospital_job_configuration.json
COPY ../internal_servers/job-configurations-schema.generated.json ./internal_servers/job-configurations-schema.generated.json
COPY receiver_loop.py /app/internal_servers/receiver_loop.py

# Set the PYTHON_PATH environment variable
ENV PYTHONPATH=/app/internal_servers
ENV DOCKER_ENV=1
ARG DEBIAN_FRONTEND=noninteractive
ARG API_KEY
ARG BACKEND_URL
ARG ORTHANC_URL

CMD ["python3", "internal_servers/receiver_loop.py", "--api_key", "${API_KEY}", "--backend_url", "${BACKEND_URL}", "--orthanc_url", "${ORTHANC_URL}", "--hospital_mapping_file", "/app/internal_servers/hospital_job_configuration.json", "--study_config_file", "/app/internal_servers/job-configurations-schema.generated.json"]
