apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-creator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator-role
rules:
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
subjects:
- kind: ServiceAccount
  name: job-creator-account
  namespace: default
roleRef:
  kind: Role
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io

