apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: receiver_loop:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "/app/small_k8s_system/receiver_loop.py"]
        args: [
          "--api_key", "$(API_KEY)",
          "--backend_url", "$(BACKEND_URL)",
          "--orthanc_url", "$(ORTHANC_URL)",
          "--hospital_mapping_file", "/app/small_k8s_system/hospital_job_configuration.json",
          "--study_config_file", "/app/small_k8s_system/job-configurations-schema.generated.json"
        ]
        env:
        - name: API_KEY
#          valueFrom:
#            secretKeyRef:
#              name: api-key-secret
#              key: api_key
          value: 'dummyvalue'
        - name: BACKEND_URL
          value: "http://backend-service.default.svc.cluster.local"  # Adjust as necessary
        - name: ORTHANC_URL
          value: "http://orthanc-service.default.svc.cluster.local:8026"
        resources:
          requests:
            cpu: "100m"  # 100 millicpu (0.1 CPU cores)
            memory: "100Mi"  # 100 MiB
          limits:
            cpu: "200m"
            memory: "200Mi"
