"""Create metadata configruations table

Revision ID: 3624be4e7aed
Revises: 3b7af80b4593
Create Date: 2023-04-26 20:09:11.462929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3624be4e7aed"
down_revision = "3b7af80b4593"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(), nullable=False),
        sa.Column("field_type", sa.String(), nullable=False),
        sa.Column("field_value", sa.String(), nullable=False),
        sa.Column("field_units", sa.String(), nullable=False),
        sa.Column("step_configuration_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["step_configuration_id"],
            ["step_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("step_configuration_id"),
    )
    op.create_index(
        op.f("ix_metadata_configurations_field_name"),
        "metadata_configurations",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_field_type"),
        "metadata_configurations",
        ["field_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_field_units"),
        "metadata_configurations",
        ["field_units"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_field_value"),
        "metadata_configurations",
        ["field_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_id"),
        "metadata_configurations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_step_configuration_id"),
        "metadata_configurations",
        ["step_configuration_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_metadata_configurations_step_configuration_id"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_id"), table_name="metadata_configurations"
    )
    op.drop_index(
        op.f("ix_metadata_configurations_field_value"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_field_units"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_field_type"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_field_name"),
        table_name="metadata_configurations",
    )
    op.drop_table("metadata_configurations")
    # ### end Alembic commands ###
