"""add metadata_column

Revision ID: 408b1c104fdf
Revises: b32b411f19a2
Create Date: 2023-04-15 11:46:25.793397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '408b1c104fdf'
down_revision = 'b32b411f19a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_metadata')
    # ### end Alembic commands ###
