"""Add job_configuration_id column

Revision ID: 4852f79e6d5f
Revises: affc3e689080
Create Date: 2023-04-29 15:14:29.174254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4852f79e6d5f'
down_revision = 'affc3e689080'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_configuration_id', sa.Integer(), nullable=True))
    op.alter_column('jobs', 'provider_job_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_jobs_job_configuration_id'), 'jobs', ['job_configuration_id'], unique=False)
    op.create_foreign_key('fk_jobs_job_configuration_id', 'jobs', 'job_configurations', ['job_configuration_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_jobs_job_configuration_id", 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_job_configuration_id'), table_name='jobs')
    op.alter_column('jobs', 'provider_job_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('jobs', 'job_configuration_id')
    # ### end Alembic commands ###
