"""Added version and field value columns

Revision ID: 56aba86029e5
Revises: fb30fde8b374
Create Date: 2023-04-22 18:37:32.419082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56aba86029e5"
down_revision = "fb30fde8b374"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_configurations", sa.Column("version", sa.String(), nullable=False)
    )
    op.drop_constraint(
        "job_configurations_provider_id_tag_key", "job_configurations", type_="unique"
    )
    op.create_index(
        op.f("ix_job_configurations_version"),
        "job_configurations",
        ["version"],
        unique=False,
    )
    op.create_unique_constraint(
        None, "job_configurations", ["provider_id", "tag", "version"]
    )
    op.add_column(
        "metadata_configurations",
        sa.Column("provider_field_value", sa.String(), nullable=False),
    )
    op.add_column(
        "metadata_configurations",
        sa.Column("step_configuration_id", sa.Integer(), nullable=False),
    )
    op.drop_index(
        "ix_metadata_configurations_provider_step_configuration_id",
        table_name="metadata_configurations",
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_field_value"),
        "metadata_configurations",
        ["provider_field_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_step_configuration_id"),
        "metadata_configurations",
        ["step_configuration_id"],
        unique=False,
    )
    op.drop_constraint(
        "metadata_configurations_provider_step_configuration_id_fkey",
        "metadata_configurations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "metadata_configurations",
        "step_configurations",
        ["step_configuration_id"],
        ["id"],
    )
    op.drop_column("metadata_configurations", "provider_step_configuration_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metadata_configurations",
        sa.Column(
            "provider_step_configuration_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "metadata_configurations", type_="foreignkey")
    op.create_foreign_key(
        "metadata_configurations_provider_step_configuration_id_fkey",
        "metadata_configurations",
        "step_configurations",
        ["provider_step_configuration_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_metadata_configurations_step_configuration_id"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_provider_field_value"),
        table_name="metadata_configurations",
    )
    op.create_index(
        "ix_metadata_configurations_provider_step_configuration_id",
        "metadata_configurations",
        ["provider_step_configuration_id"],
        unique=False,
    )
    op.drop_column("metadata_configurations", "step_configuration_id")
    op.drop_column("metadata_configurations", "provider_field_value")
    op.drop_constraint(None, "job_configurations", type_="unique")
    op.drop_index(
        op.f("ix_job_configurations_version"), table_name="job_configurations"
    )
    op.create_unique_constraint(
        "job_configurations_provider_id_tag_key",
        "job_configurations",
        ["provider_id", "tag"],
    )
    op.drop_column("job_configurations", "version")
    # ### end Alembic commands ###
