"""Create metadata_configurations table

Revision ID: 84cde042f5a0
Revises: a815badd99e6
Create Date: 2023-04-16 21:24:44.493784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84cde042f5a0"
down_revision = "a815badd99e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_tag", sa.String(), nullable=False),
        sa.Column("event_tag", sa.String(), nullable=False),
        sa.Column("provider_field_name", sa.String(), nullable=False),
        sa.Column("provider_field_type", sa.String(), nullable=False),
        sa.Column("provider_field_units", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metadata_configurations_event_tag"),
        "metadata_configurations",
        ["event_tag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_id"),
        "metadata_configurations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_job_tag"),
        "metadata_configurations",
        ["job_tag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_field_name"),
        "metadata_configurations",
        ["provider_field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_field_type"),
        "metadata_configurations",
        ["provider_field_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_field_units"),
        "metadata_configurations",
        ["provider_field_units"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_metadata_configurations_provider_field_units"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_provider_field_type"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_provider_field_name"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_job_tag"), table_name="metadata_configurations"
    )
    op.drop_index(
        op.f("ix_metadata_configurations_id"), table_name="metadata_configurations"
    )
    op.drop_index(
        op.f("ix_metadata_configurations_event_tag"),
        table_name="metadata_configurations",
    )
    op.drop_table("metadata_configurations")
    # ### end Alembic commands ###
