"""Create job configruations table

Revision ID: 9109499a271e
Revises: b6bcaa15f3ed
Create Date: 2023-04-26 20:02:31.508162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9109499a271e"
down_revision = "6e69f4231372"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "tag", "version"),
    )
    op.create_index(
        op.f("ix_job_configurations_id"), "job_configurations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_job_configurations_name"), "job_configurations", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_job_configurations_provider_id"),
        "job_configurations",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_configurations_tag"), "job_configurations", ["tag"], unique=False
    )
    op.create_index(
        op.f("ix_job_configurations_version"),
        "job_configurations",
        ["version"],
        unique=False,
    )
    op.add_column(
        "jobs", sa.Column("job_configuration_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_jobs_job_configuration_id"),
        "jobs",
        ["job_configuration_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "jobs", "job_configurations", ["job_configuration_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_index(op.f("ix_jobs_job_configuration_id"), table_name="jobs")
    op.drop_column("jobs", "job_configuration_id")
    op.drop_index(
        op.f("ix_job_configurations_version"), table_name="job_configurations"
    )
    op.drop_index(op.f("ix_job_configurations_tag"), table_name="job_configurations")
    op.drop_index(
        op.f("ix_job_configurations_provider_id"), table_name="job_configurations"
    )
    op.drop_index(op.f("ix_job_configurations_name"), table_name="job_configurations")
    op.drop_index(op.f("ix_job_configurations_id"), table_name="job_configurations")
    op.drop_table("job_configurations")
    # ### end Alembic commands ###
