"""create_jobs_table

Revision ID: 9417ea6019b1
Revises: 19eb77a561bd
Create Date: 2023-03-22 02:26:17.709741

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9417ea6019b1"
down_revision = "19eb77a561bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_job_id", sa.String(), nullable=False),
        sa.Column("client_job_kind", sa.String(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jobs_client_job_id"), "jobs", ["client_job_id"], unique=False
    )
    op.create_index(
        op.f("ix_jobs_client_job_kind"), "jobs", ["client_job_kind"], unique=False
    )
    op.create_index(op.f("ix_jobs_customer_id"), "jobs", ["customer_id"], unique=False)
    op.create_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_customer_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_client_job_kind"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_client_job_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
