"""Create job_configurations table

Revision ID: 96a0d2615fae
Revises: b32b411f19a2
Create Date: 2023-04-16 20:15:28.416187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96a0d2615fae"
down_revision = "b32b411f19a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("provider_job_configuration_name", sa.String(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "tag"),
    )
    op.create_index(
        op.f("ix_job_configurations_id"), "job_configurations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_job_configurations_provider_id"),
        "job_configurations",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_configurations_provider_job_configuration_name"),
        "job_configurations",
        ["provider_job_configuration_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_configurations_tag"), "job_configurations", ["tag"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_configurations_tag"), table_name="job_configurations")
    op.drop_index(
        op.f("ix_job_configurations_provider_job_configuration_name"),
        table_name="job_configurations",
    )
    op.drop_index(
        op.f("ix_job_configurations_provider_id"), table_name="job_configurations"
    )
    op.drop_index(op.f("ix_job_configurations_id"), table_name="job_configurations")
    op.drop_table("job_configurations")
    # ### end Alembic commands ###
