"""Create events_configurations table

Revision ID: a815badd99e6
Revises: 96a0d2615fae
Create Date: 2023-04-16 21:11:43.737532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a815badd99e6"
down_revision = "96a0d2615fae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_tag", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("provider_event_configuration_name", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "step", "error", "info", "complete", name="event_configuration_kind"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    op.create_index(
        op.f("ix_event_configurations_id"), "event_configurations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_event_configurations_job_tag"),
        "event_configurations",
        ["job_tag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_configurations_provider_event_configuration_name"),
        "event_configurations",
        ["provider_event_configuration_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_configurations_tag"),
        "event_configurations",
        ["tag"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_event_configurations_tag"), table_name="event_configurations"
    )
    op.drop_index(
        op.f("ix_event_configurations_provider_event_configuration_name"),
        table_name="event_configurations",
    )
    op.drop_index(
        op.f("ix_event_configurations_job_tag"), table_name="event_configurations"
    )
    op.drop_index(op.f("ix_event_configurations_id"), table_name="event_configurations")
    op.drop_table("event_configurations")
    # ### end Alembic commands ###
