"""Updated uniqueness constraints for configs

Revision ID: b5e2986b75e2
Revises: 56aba86029e5
Create Date: 2023-04-22 20:11:16.412768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5e2986b75e2"
down_revision = "56aba86029e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "metadata_configurations", ["step_configuration_id"]
    )
    op.drop_constraint(
        "step_configurations_tag_key", "step_configurations", type_="unique"
    )
    op.create_unique_constraint(
        None, "step_configurations", ["job_configuration_id", "tag"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "step_configurations", type_="unique")
    op.create_unique_constraint(
        "step_configurations_tag_key", "step_configurations", ["tag"]
    )
    op.drop_constraint(None, "metadata_configurations", type_="unique")
    # ### end Alembic commands ###
