"""Create metadata configurations table

Revision ID: b9d97bd3255a
Revises: c800c9557828
Create Date: 2023-04-19 07:56:09.557047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b9d97bd3255a"
down_revision = "c800c9557828"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metadata_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_tag", sa.String(), nullable=False),
        sa.Column("step_tag", sa.String(), nullable=False),
        sa.Column("provider_field_name", sa.String(), nullable=False),
        sa.Column("provider_field_type", sa.String(), nullable=False),
        sa.Column("provider_field_units", sa.String(), nullable=False),
        sa.Column("provider_step_configuration_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_step_configuration_id"],
            ["step_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metadata_configurations_id"),
        "metadata_configurations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_job_tag"),
        "metadata_configurations",
        ["job_tag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_field_name"),
        "metadata_configurations",
        ["provider_field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_field_type"),
        "metadata_configurations",
        ["provider_field_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_field_units"),
        "metadata_configurations",
        ["provider_field_units"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_provider_step_configuration_id"),
        "metadata_configurations",
        ["provider_step_configuration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_configurations_step_tag"),
        "metadata_configurations",
        ["step_tag"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_metadata_configurations_step_tag"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_provider_step_configuration_id"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_provider_field_units"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_provider_field_type"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_provider_field_name"),
        table_name="metadata_configurations",
    )
    op.drop_index(
        op.f("ix_metadata_configurations_job_tag"), table_name="metadata_configurations"
    )
    op.drop_index(
        op.f("ix_metadata_configurations_id"), table_name="metadata_configurations"
    )
    op.drop_table("metadata_configurations")
    # ### end Alembic commands ###
