"""Create step configurations table

Revision ID: c800c9557828
Revises: 18f2520ef173
Create Date: 2023-04-19 07:50:36.695686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c800c9557828"
down_revision = "18f2520ef173"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "step_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_tag", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("provider_step_configuration_name", sa.String(), nullable=False),
        sa.Column("provider_job_configuration_id", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_job_configuration_id"],
            ["job_configurations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    op.create_index(
        op.f("ix_step_configurations_id"), "step_configurations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_step_configurations_job_tag"),
        "step_configurations",
        ["job_tag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_step_configurations_points"),
        "step_configurations",
        ["points"],
        unique=False,
    )
    op.create_index(
        op.f("ix_step_configurations_provider_job_configuration_id"),
        "step_configurations",
        ["provider_job_configuration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_step_configurations_provider_step_configuration_name"),
        "step_configurations",
        ["provider_step_configuration_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_step_configurations_tag"), "step_configurations", ["tag"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_step_configurations_tag"), table_name="step_configurations")
    op.drop_index(
        op.f("ix_step_configurations_provider_step_configuration_name"),
        table_name="step_configurations",
    )
    op.drop_index(
        op.f("ix_step_configurations_provider_job_configuration_id"),
        table_name="step_configurations",
    )
    op.drop_index(
        op.f("ix_step_configurations_points"), table_name="step_configurations"
    )
    op.drop_index(
        op.f("ix_step_configurations_job_tag"), table_name="step_configurations"
    )
    op.drop_index(op.f("ix_step_configurations_id"), table_name="step_configurations")
    op.drop_table("step_configurations")
    # ### end Alembic commands ###
