"""Update job and step columns

Revision ID: cbc848de23a0
Revises: b9d97bd3255a
Create Date: 2023-04-19 19:47:27.588871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbc848de23a0"
down_revision = "b9d97bd3255a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "job_configurations", ["provider_id", "tag"])
    op.add_column(
        "step_configurations",
        sa.Column("job_configuration_id", sa.Integer(), nullable=False),
    )
    op.drop_index(
        "ix_step_configurations_provider_job_configuration_id",
        table_name="step_configurations",
    )
    op.create_index(
        op.f("ix_step_configurations_job_configuration_id"),
        "step_configurations",
        ["job_configuration_id"],
        unique=False,
    )
    op.drop_constraint(
        "step_configurations_provider_job_configuration_id_fkey",
        "step_configurations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "step_configurations",
        "job_configurations",
        ["job_configuration_id"],
        ["id"],
    )
    op.drop_column("step_configurations", "provider_job_configuration_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "step_configurations",
        sa.Column(
            "provider_job_configuration_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "step_configurations", type_="foreignkey")
    op.create_foreign_key(
        "step_configurations_provider_job_configuration_id_fkey",
        "step_configurations",
        "job_configurations",
        ["provider_job_configuration_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_step_configurations_job_configuration_id"),
        table_name="step_configurations",
    )
    op.create_index(
        "ix_step_configurations_provider_job_configuration_id",
        "step_configurations",
        ["provider_job_configuration_id"],
        unique=False,
    )
    op.drop_column("step_configurations", "job_configuration_id")
    op.drop_constraint(None, "job_configurations", type_="unique")
    # ### end Alembic commands ###
