# Use a Python 3.10 image based on Debian slim as the base
FROM python:3.10-slim
LABEL authors="mbrzus and iejohnson"

WORKDIR /app
RUN apt-get update --fix-missing && \
    apt-get install -y --fix-missing \
    python3-dev \
    inetutils-ping \
    curl \
    net-tools \
    dnsutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install the Python dependencies
RUN pip3 install --no-cache-dir pyorthanc typing_extensions requests kubernetes

# Copy the executable script into the container
COPY aws_cluster/study/hospital_job_configuration.json /app/internal_servers/hospital_job_configuration.json
#COPY job-configurations-schema.generated.json /app/internal_servers/job-configurations-schema.generated.json
COPY aws_cluster/listening/receiver_loop.py /app/internal_servers/receiver_loop.py
COPY aws_cluster/util_functions.py /app/internal_servers/util_functions.py

# Set the PYTHON_PATH environment variable
ENV PYTHONPATH=/app/internal_servers
#ENV DOCKER_ENV=1
#ARG DEBIAN_FRONTEND=noninteractive
#ARG API_KEY
#ARG BACKEND_URL
#ARG ORTHANC_URL

# Set default parameters that can be overridden
ENTRYPOINT ["python", "/app/internal_servers/receiver_loop.py"]
