# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

LABEL maintainer="mbrzus"
LABEL version="0.1"
LABEL description="This is the Dockerfile for the small Kubernetes script"

# Set the working directory in the container
WORKDIR /app

# Install necessary libraries
RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Upgrade pip
RUN python3 -m pip install --upgrade pip

# Install Python dependencies
# Assuming you're using Kubernetes Python client; adjust accordingly
RUN pip install kubernetes pyorthanc requests pydantic==1.10.5

# Copy the script into the container
COPY study.py .
COPY test_data /app/test_data
COPY ./util_functions.py /app/util_functions.py
COPY study_tracking.py /app/study_tracking.py
COPY trackerapi /app/trackerapi
COPY hospital_job_configuration.json /app/internal_servers/hospital_job_configuration.json

# You don't need to create input/output directories in the container, as these will be
# provided by Kubernetes volumes mounted into the Pod that runs this container.

# Set an environment variable for the Kubernetes configuration file, if needed
# ENV KUBECONFIG /path/to/kubeconfig

ENTRYPOINT ["python", "study.py"]
